apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/websocket-services: "trip-service"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/websocket-services: "trip-service"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: brototypes.com
    http:
      paths:
      - path: /api/fumigation/?(.*)
        pathType: Prefix
        backend:
          service:
            name: fumigation-service
            port:
              number: 3002
      - path: /?(.*)
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 5173
      - path: /api/student/?(.*)
        pathType: Prefix
        backend:
          service:
            name: student-service
            port:
              number: 4000
      - path: /api/auth/?(.*)
        pathType: Prefix
        backend:
          service:
            name: authentication-service
            port:
              number: 6002
      - path: /api/task/?(.*)
        pathType: Prefix
        backend:
          service:
            name: task-service
            port:
              number: 7001
      - path: /api/superlead/?(.*)
        pathType: Prefix
        backend:
          service:
            name: superlead-service
            port:
              number: 8001
      - path: /api/chat-and-video/?(.*)
        pathType: Prefix
        backend:
          service:
            name: chat-and-video-service
            port:
              number: 9001
      - path: /api/reviewer/?(.*)
        pathType: Prefix
        backend:
          service:
            name: reviewer-service
            port:
              number: 5001
      - path: /review-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: review-service
            port:
              number: 6001
      - path: /socket.io/
        pathType: Prefix
        backend:
          service:
            name: chat-and-video-service
            port:
              number: 9001
      - path: /admin-service/?(.*)
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 3000
  ingressClassName: nginx
