name: deploy-admin-service

on:
  push:
    branches:
      - main
    paths:
      - "BACKEND/admin-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variables for Admin Service
        env:
          ADMIN_MONGO_URL: ${{ secrets.ADMIN_MONGO_URL }}
          ADMIN_SERVER_PORT: ${{ secrets.ADMIN_SERVER_PORT }}

        run: |
          echo "ADMIN_MONGO_URL=${ADMIN_MONGO_URL}" >> BACKEND/admin-service/.env
          echo "ADMIN_SERVER_PORT=${ADMIN_SERVER_PORT}" >> BACKEND/admin-service/.env

      - run: cd BACKEND/admin-service/ && docker build -t officialrashid/admin-service:latest .

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push officialrashid/admin-service:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save 6ba6c2ad-d2de-4395-95a6-968768b137df

      - run: kubectl rollout restart deployment admin-deployment
