name: deploy-superlead-service

on:
  push:
    branches:
      - main
    paths:
      - "BACKEND/superlead-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variables for Superlead Service
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          SUPERLEAD_MONGO_URL: ${{ secrets.SUPERLEAD_MONGO_URL }}
          SUPERLEAD_SERVER_PORT: ${{ secrets.SUPERLEAD_SERVER_PORT }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_SUPERLEAD_BUCKET_NAME: ${{ secrets.S3_SUPERLEAD_BUCKET_NAME }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
          FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}

        run: |
          echo "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}" >> BACKEND/superlead-service/.env
          echo "SUPERLEAD_MONGO_URL=${SUPERLEAD_MONGO_URL}" >> BACKEND/superlead-service/.env
          echo "SUPERLEAD_SERVER_PORT=${SUPERLEAD_SERVER_PORT}" >> BACKEND/superlead-service/.env
          echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}" >> BACKEND/superlead-service/.env
          echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}" >> BACKEND/superlead-service/.env
          echo "S3_SUPERLEAD_BUCKET_NAME=${S3_SUPERLEAD_BUCKET_NAME}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}" >> BACKEND/superlead-service/.env
          echo "FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}" >> BACKEND/superlead-service/.env

      - run: cd BACKEND/superlead-service/ && docker build -t officialrashid/superlead-service:latest .

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push officialrashid/superlead-service:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save c4587a70-8120-4519-94e0-5c7aa5da0df5

      - run: kubectl rollout restart deployment superlead-deployment
