name: deploy-client-service

on:
  push:
    branches:
      - main
    paths:
      - "FRONTEND/Brototype-Frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
   
      - run: cd FRONTEND/Brototype-Frontend/ && docker build -t officialrashid/client-service:latest .

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push officialrashid/client-service:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save e0fc6e9b-4857-4017-a874-db7359838fc9

      - run: kubectl rollout restart deployment client-deployment
