name: deploy-student-service

on:
  push:
    branches:
      - main
    paths:
      - "BACKEND/student-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment variables for Student Service
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          STUDENT_MONGO_URL: ${{ secrets.STUDENT_MONGO_URL }}
          STUDENT_SERVER_PORT: ${{ secrets.STUDENT_SERVER_PORT }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_STUDENT_AADHAR_BUCKET_NAME: ${{ secrets.S3_STUDENT_AADHAR_BUCKET_NAME }}
          S3_STUDENT_BUCKET_NAME: ${{ secrets.S3_STUDENT_BUCKET_NAME }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
          FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}

        run: |
          echo "ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}" >> BACKEND/student-service/.env
          echo "STUDENT_MONGO_URL=${STUDENT_MONGO_URL}" >> BACKEND/student-service/.env
          echo "STUDENT_SERVER_PORT=${STUDENT_SERVER_PORT}" >> BACKEND/student-service/.env
          echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}" >> BACKEND/student-service/.env
          echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}" >> BACKEND/student-service/.env
          echo "S3_STUDENT_AADHAR_BUCKET_NAME=${S3_STUDENT_AADHAR_BUCKET_NAME}" >> BACKEND/student-service/.env
          echo "S3_STUDENT_BUCKET_NAME=${S3_STUDENT_BUCKET_NAME}" >> BACKEND/student-service/.env
          echo "FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}" >> BACKEND/student-service/.env
          echo "FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}" >> BACKEND/student-service/.env
          echo "FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}" >> BACKEND/student-service/.env
          echo "FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}" >> BACKEND/student-service/.env
          echo "FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}" >> BACKEND/student-service/.env
          echo "FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}" >> BACKEND/student-service/.env
          echo "FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}" >> BACKEND/student-service/.env

      - run: cd BACKEND/student-service/ && docker build -t officialrashid/student-service:latest .

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push officialrashid/student-service:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save 6ba6c2ad-d2de-4395-95a6-968768b137df

      - run: kubectl rollout restart deployment student-deployment
